<?php
/**
 * Palette Selector Component
 *
 * @package WoowAdmin
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Note: Palettes are loaded via JavaScript from woowAdminData.palettes
// This component provides the container and category filters
$current_palette = $settings['general']['current_palette'] ?? 'professional_blue';
?>

<div class="woow-palette-selector">
    <!-- Category Filters -->
    <div class="woow-palette-filters">
        <!-- Filters will be dynamically generated by JavaScript -->
    </div>
    
    <!-- Palette Grid -->
    <div class="woow-palette-grid">
        <!-- Palette cards will be dynamically generated by JavaScript -->
        <div class="woow-palette-loading">
            <span class="dashicons dashicons-update-alt"></span>
            <p><?php esc_html_e( 'Loading palettes...', 'woow-admin' ); ?></p>
        </div>
    </div>
</div>
