<?php
/**
 * Template Gallery Component
 *
 * @package WoowAdmin
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Note: Templates are loaded via JavaScript from woowAdminData.templates
// This component provides the container and category filters
$current_template = $settings['general']['current_template'] ?? 'modern_minimal';
?>

<div class="woow-template-selector">
    <!-- Category Filters -->
    <div class="woow-template-filters">
        <!-- Filters will be dynamically generated by JavaScript -->
    </div>
    
    <!-- Template Grid -->
    <div class="woow-template-grid">
        <!-- Template cards will be dynamically generated by JavaScript -->
        <div class="woow-template-loading">
            <span class="dashicons dashicons-update-alt"></span>
            <p><?php esc_html_e( 'Loading templates...', 'woow-admin' ); ?></p>
        </div>
    </div>
</div>
